### ISSUE TITLE
Is it possible to have latest blog post appear on www.openampproject.org main page?

### ISSUE THREAD

**Issue by nathalie-ckc** [OpenAMP/website#96]
Hi @kylekirkby , 

Got a suggestion from @wmamills in PR #94 that it would be helpful if the latest blog post appeared on the www.openampproject.org main page, if it is <6 mo old.  Is that feasible?  

Thanks & regards,
Nathalie

**Comment by wmamills** [comment]
@kylekirkby is the above possible/easy?

**Comment by nathalie-ckc** [comment]
Hi @kylekirkby , following up on the question from @wmamills .

**Comment by wmamills** [comment]
Hi @louismorgan-linaro .  Good question.  If you have existing examples of this please point to them.

We will need @nathalie-ckc 's input as well but looking at the page, perhaps we could have a sliding jumbotro in the black trangle area.  It should start with the existing content (Logo Text and github button) but them after N seconds go a card of the most recent blog and the again after N go to the 2nd most recent and then back to the original content.

Is that doable?

**Comment by DelaraGi** [comment]
Hi @wmamills ,
Yes, it is possible to implement a sliding jumbotron as described in your message.

**Comment by wmamills** [comment]
@DelaraGi @pcolmer Hey just noticed this was Live.  Looks good!

@nathalie-ckc take a look and close this issue if you approve as I do.

**Comment by pcolmer** [comment]
If you don't want the blog posts to remove that hero banner, we can move them lower down the page. Personally, I think the "<" and ">" symbols might be a bit hard to see over that background and it might not be intuitive as to what you are going to get by scrolling sideways.

An alternative approach would be to have 3 "cards" of the latest posts, like the Linaro does but maybe not so tall?

![image](https://github.com/OpenAMP/website/assets/1979931/a0ab6194-bc56-4a5b-a275-a42241636ee8)

If you want to see what that might look like, we can do it as a pull request so that a preview site gets built for comparison.

**Comment by nathalie-ckc** [comment]
@pcolmer , if it's not too much trouble, your idea sounds interesting & would be interested to see it as a PR preview site.

**Comment by pcolmer** [comment]
@nathalie-ckc being tracked at https://linaro.atlassian.net/browse/WEBDEV-1465

**Comment by pcolmer** [comment]
@nathalie-ckc please see https://production-openampproject-org-113.ghactions.linaro.org/ for a preview of the suggested alternative approach.

**Comment by nathalie-ckc** [comment]
Thanks @pcolmer , looks good to me.  
@wmamills please comment, as you had thoughts on the topic during today's OpenAMP Board call.

**Comment by nathalie-ckc** [comment]
Addressed by PR #109 and #111
